@startuml
title 物联网边缘计算系统架构图

cloud {
   [互联网]
}

node "外部系统设备" {
  [LCD仪表盘]
}


node "视频采集" {
   [高清可变焦摄像头]
}

[LCD仪表盘] --> [高清可变焦摄像头]

node "视频采集层" {
   [图形采集程序]
}

[高清可变焦摄像头] --> [图形采集程序]

node "图像加工" {
   [图像裁剪]
   [图像旋转]
   [图像灰度化]
   [图像分类]

}

 node "OCR识别模块" {
             [图片转文字]

          }

[图形采集程序]--> [图像裁剪]




[图像分类] -->  [图片转文字]

node "数据格式封装" {
     folder "智能容错" {
     [识别关键属性准确度]
     }
     folder "数据封装" {
      [JSON数据格式]
     }
}

[图片转文字] --> [识别关键属性准确度]
[识别关键属性准确度] --> [JSON数据格式]

node "数据生产者" {
   [数据生产者(MQTT客户端)]
}

[JSON数据格式] --> [数据生产者(MQTT客户端)]

node "MQTT服务器" {
    [RabbitMQ服务器]
}


node "数据消费者(其他应用程序)" {
     [MQTT消费者]
}

[数据生产者(MQTT客户端)] --> [RabbitMQ服务器]

[MQTT消费者] --> [RabbitMQ服务器]

[数据生产者(MQTT客户端)]<--[用户自定义配置文件]


folder "用户自定义配置文件" {
     [MQTT服务器IP]
     [图形识别算法]
     [图形相识度阀值]
     [JSON模版文件]
     [MQTT用户和密码]

    }

node "树莓派3" {
   folder "docker运行环境" {
     [docker引擎]
   }
}


@enduml